CREATE TABLE Admins (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(MAX) NOT NULL,
    HashedPassword NVARCHAR(MAX) NOT NULL,
    Role INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL
);

CREATE TABLE Categories (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Slug NVARCHAR(255) NOT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL
);

CREATE TABLE Discounts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    DiscountCode NVARCHAR(MAX) NOT NULL,
    DiscountPercentage DECIMAL(18,2) NOT NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    UsageLimit INT NOT NULL,
    TimesUsed INT NOT NULL,
    Status INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL
);

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(255) NOT NULL,
    BirthYear DATETIME2 NOT NULL,
    Gender INT NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    HashedPassword NVARCHAR(255) NOT NULL,
    AvatarPath NVARCHAR(MAX) NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    Status INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL
);

CREATE TABLE Products (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Brand NVARCHAR(100) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    CategoryId INT NOT NULL,
    Cpu NVARCHAR(100) NOT NULL,
    Ram NVARCHAR(50) NOT NULL,
    Vga NVARCHAR(100) NOT NULL,
    ScreenSize NVARCHAR(50) NOT NULL,
    HardDisk NVARCHAR(100) NOT NULL,
    Os NVARCHAR(50) NOT NULL,
    Price DECIMAL(12,0) NOT NULL,
    Stock INT NOT NULL,
    Image NVARCHAR(MAX) NOT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
);

CREATE TABLE Orders (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    OrderDate DATETIME2 NOT NULL,
    TotalPrice DECIMAL(12,0) NOT NULL,
    Payment INT NOT NULL,
    Status INT NOT NULL,
    DiscountId INT NULL,
    CreatedDate DATETIME2 NOT NULL,
    LastModifiedDate DATETIME2 NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (DiscountId) REFERENCES Discount(Id)
);

CREATE TABLE OrderDetails (
    OrderId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(12,0) NOT NULL,
    PRIMARY KEY (OrderId, ProductId),
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE
);
